version: "3"

services:
  app:
    build: .
    env_file:
      - ./config/.env
    ports:
      - 80:5000
    links:
      - mysqldb
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
