version: '3'

services: 
  app:
    build: .
    env_file: 
      - ./config/.env
    ports: 
      - 80:5000
    links: 
      - mongodb
    depends_on: 
      - mongodb
  mongodb:
    image: mongo
    ports: 
      - 27017:27017